# Web Sunucusu Portu
server.port=8080

# PostgreSQL Veritaban? Ba?lant? Ayarlar?
spring.datasource.url=jdbc:postgresql://localhost:5432/hie
spring.datasource.username=postgres
spring.datasource.password=postgresql



# PostgreSQL Sürücüsü
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Ayarlar?
# update: Tablo yoksa olu?turur, varsa sadece yeni eklenen sütunlar? günceller.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Sonradan eklenenler----------

# Spring Mail Ayarlar?
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=senin_test_mailin@gmail.com
spring.mail.password=senin_uygulama_sifren

# SMTP Güvenlik Protokolleri
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000